<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Krafs.Publicizer" PrivateAssets="true" Version="2.2.1" />
		<Publicize Include="tModLoader" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
		<Publicize Include="tModLoader;FNA" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="ShopExpander">
	    <HintPath>..\ModAssemblies\ShopExpander_v1.8.1.dll</HintPath>
	  </Reference>
	</ItemGroup>


</Project>