<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	</PropertyGroup>
	<ItemGroup>
	  <Reference Include="ShopExtender">
	    <HintPath>..\ModAssemblies\ShopExtender_v1.0.0.2.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Krafs.Publicizer" PrivateAssets="true" Version="2.2.1" />
		<Publicize Include="tModLoader" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
		<Publicize Include="tModLoader;FNA" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
	</ItemGroup>
	
	

</Project>