<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
	  <None Remove="Assets\BeamBody.png" />
	  <None Remove="Assets\BeamEnd.png" />
	  <None Remove="Assets\BloodOrb.png" />
	  <None Remove="Assets\BloodOrbSmol.png" />
	  <None Remove="Assets\CDFiller.png" />
	  <None Remove="Assets\CDTex.png" />
	  <None Remove="Assets\WheelExtra.png" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Content\Items\Acessories\" />
	</ItemGroup>


</Project>